### ISSUE TITLE
Proof of Concept Checklist

### ISSUE THREAD

**Issue by fabiankaegy** [fabiankaegy/wp-wasm-deploy-preview-example#1]
- [ ] Run WordPress Playground on a GitHub Pages hosted static page
- [ ] Add a comment to any opened PR containing a link to the GitHub Pages site
- [ ] Pass a param with the relevant build information to the GitHub Pages hostes site
